{% set version = "1.6.1" %}

package:
  name: perf
  version: {{ version }}

source:
  url: https://github.com/vstinner/pyperf/archive/{{ version }}.tar.gz
  sha256: fbe793f6f2e036ab4dcca105b5c5aa34fd331dd881e7a3e158e5e218c63cfc32

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyperf = perf.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - perf
  commands:
    - pyperf --help

about:
  home: https://github.com/vstinner/pyperf
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "Toolkit to run Python benchmarks"
  doc_url: https://pyperf.readthedocs.io/en/latest/
  dev_url: https://github.com/vstinner/pyperf

extra:
  recipe-maintainers:
    - dougalsutherland
