{% set version = "1.7.0" %}

package:
  name: perf
  version: {{ version }}

source:
  url: https://github.com/vstinner/pyperf/archive/{{ version }}.tar.gz
  sha256: 67caab39f99f34fd6387dd59e63bb498a941d8e2da3cd389fbfc8d4d6bf5e97e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - pyperf = perf.__main__:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - statistics  # [py2k]

test:
  imports:
    - perf
  commands:
    - pyperf --help

about:
  home: https://github.com/vstinner/pyperf
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: "Toolkit to run Python benchmarks"
  doc_url: https://pyperf.readthedocs.io/en/latest/
  dev_url: https://github.com/vstinner/pyperf

extra:
  recipe-maintainers:
    - dougalsutherland
